### ISSUE TITLE
only run the content script on issues

### ISSUE THREAD

**Issue by groovecoder** [codesy/old-firefox-addon#1]
The [`match-pattern` module](https://addons.mozilla.org/en-US/developers/docs/sdk/latest/modules/sdk/util/match-pattern.html) of the Add-on SDK landed in Firefox 25 which is now released.

We should update the add-on to use `match-pattern` to only run the content script on issues pages.

**Comment by mwic** [comment]
is match-pattern overkill ? How about :
include: "https://github.com/*/issues/*"
in the PageMod call ?

**Comment by groovecoder** [comment]
Re-reading [the docs on PageMod](https://addons.mozilla.org/en-US/developers/docs/sdk/latest/modules/sdk/page-mod.html#PageMod%28options%29), I think you're right - and the match-pattern module might be in inherent in the constructor. Feel free to give it a try? :)

**Comment by mwic** [comment]
Asked about this, got lots of views but I couldn't get any answers: https://forums.mozilla.org/addons/viewtopic.php?f=7&t=15470 
I've tried several variations and the string "https://github.com/*" is the only one that I could get to trigger the actual pagemod.
